[build]
  command = "npm run build"
  publish = ".next"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[[redirects]]
  from = "/netlify/:query"
  to = "https://www.google.com/search?q=:query"
  status = 301
  force = true